### PR TITLE
Added Env file and updated RTD.

### PR DESCRIPTION
**Pull request by rsk27**

### CODE REVIEW

**Comment by Arnav0400** [comment]
We need the requirements to have the exact version for each package in requirements.txt

**Comment by Arnav0400** [comment]
@animesh-007 can you pick this up?

**Comment by animesh-007** [comment]
> @animesh-007 can you pick this up?

Ok, will add this in my next PR.

**Comment by animesh-007** [comment]
@Arnav0400 I have updated this PR only by making a commit to it. Please review and merge accordingly.😇

**Review by Arnav0400 — APPROVED** [review]

**Pull request merged**
